#dont need this anymore, but useful for test deployment
version: '3'

services:
  info-geoconnex-us:
    build: .
    user: root
    ports:
      - "5002:80"
    restart: always
    volumes:
      - ./ref_gages.gpkg:/data/ref_gages.gpkg