# dont need this anymore, but useful for test deployment
# requires separate service providing postgres database
version: '3'

services:
  info-geoconnex-us:
    build: .
    user: root
    ports:
      - "5000:80"
    restart: always
