name: reference.geoconnex.us pygeoapi build

on:
  push:
    branches:
      - 'dev'
      - 'master'
    paths:
      - 'pygeoapi/**'

jobs:
  upload-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate sql data
        uses: cgs-earth/hydrodump-action@0.3.0
        with:
          username: ${{ secrets.HYDRO_USERNAME }}
          password: ${{ secrets.HYDRO_PASSWORD }}
          dbuser: root

      - name: Set up Cloud SDK
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Upload backup to GCP Bucket
        id: upload-files
        uses: google-github-actions/upload-cloud-storage@v0
        with:
          path: .
          destination: reference-features
          gzip: false
          parent: false
          glob: '**/*.sql.gz'
          headers: |-
            content-type: application/x-gzip


      - name: Push to mysql
        run: |-
          gcloud sql import sql reference-features gs://reference-features/reference.sql.gz \
            --verbosity=critical \
            --quiet \
            --no-user-output-enabled \
            --database=reference \
            --user=root \
            --project=${{ secrets.GCP_PROJECT_ID }}

